name: SimpleFactions
version: '${version}'

main: com.entropire.simplefactions.SimpleFactions
api-version: '26.1.1'
load: POSTWORLD

commands:
  simplefactions:
    usage: "/faction"
    description: "Main simplefactions command. Preform /f help for more help."
    aliases: [f]