name: SimpleFactions
version: '${version}'

main: com.entropire.simplefactions.SimpleFactions
api-version: '26.1.1'
load: POSTWORLD

commands:
  simplefactions:
    usage: "/simplefactions"
    aliases: [sf]